// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qthosixbvinxmmjdfuii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0aG9zaXhidmlueG1tamRmdWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNTE2NjgsImV4cCI6MjA4MjkyNzY2OH0.y9O3wosJ-EQE0rz7Hb90rj0Pz5L5lKjbsVm8GnToTaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});